### PR TITLE
docs(jest): document useful jest/eslint config

### PR DESCRIPTION
**Pull request by olance**
I suppose it's not too hard to find out on your own, but it's always great to find all the information in one place!

### CODE REVIEW

**Comment by olance** [comment]
What happened here?! 😅

**Comment by mmkal** [comment]
Lol, sorry @olance ! I mean to just merge in main, because it look like your fork last synced with main in June so GitHub Actions checks weren't running. Not sure exactly which two things are being compared now though... Let me see if I can fix.

**Comment by olance** [comment]
Oh! That's very weird, I created the PR from Github's online editor directly on the readme file 🤨

If that's easier we can close this one and I'll do it again

**Comment by mmkal** [comment]
I think it's fixed now (issue was that I changed the default branch from `master` to `main` a few months ago). Maybe you'd created your original fork before that? It looks ok now.

Have also pushed the changefile required for publishing with rush. This isn't automated yet for PRs from forks.

**Comment by olance** [comment]
> I think it's fixed now, issue was that I changed the default branch from `master` to `main` a few months ago. Maybe you'd created your original fork before that? It looks ok now.

I literally discovered your repo today 🙂 
Anyway, not big deal ^^

> Have also pushed the changefile required for publishing with rush. This isn't automated yet for PRs from forks.
Thanks for handling it!

**Pull request merged**
